Description: This patch changes the place
 where the program saves the high scores
 file. See Debian Policy 11.11. Also, adds
 changes in order to respect DESTDIR.
Forwarded: Yes
Author: Pierre Machard <pmachard@debian.org>, Josué Abarca <jmaslibre@debian.org.gt>
Bug-Debian: http://bugs.debian.org/437088
Last-Update: 2014-10-06
Index: greed/Makefile
===================================================================
--- greed.orig/Makefile
+++ greed/Makefile
@@ -2,9 +2,9 @@
 
 VERS=3.10
 
-SFILE=/usr/games/lib/greed.hs
+SFILE=$(DESTDIR)/var/games/greed/greed.hs
 # Location of game executable
-BIN=/usr/games
+BIN=$(DESTDIR)/usr/games
 
 greed: greed.c
 	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -DSCOREFILE=\"$(SFILE)\" -DRELEASE=\"$(VERS)\" -o greed greed.c -O3 -lcurses
@@ -17,10 +17,10 @@ greed.html: greed.xml
 
 install: greed.6 uninstall
 	cp greed $(BIN)
-	cp greed.6 /usr/share/man/man6/greed.6
+	cp greed.6 $(DESTDIR)/usr/share/man/man6/greed.6
 
 uninstall:
-	rm -f $(BIN)/install /usr/share/man/man6/greed.6
+	rm -f $(BIN)/greed $(DESTDIR)/usr/share/man/man6/greed.6
 
 clean:
 	rm -f *~ *.o greed greed-*.tar.gz  greed*.rpm *.html
