Description: This patch changes the place
 where the program saves the high scores
 file. See Debian Policy 11.11. Also, adds
 changes in order to respect both CC and
 CFLAGS.
Forwarded: Yes
Author: Pierre Machard <pmachard@debian.org>, Josué Abarca <jmaslibre@debian.org.gt>
Bug-Debian: http://bugs.debian.org/437088
Last-Update: 2011-01-15
--- a/Makefile
+++ b/Makefile
@@ -4,9 +4,9 @@
 
 VERS=$(shell sed <greed.spec -n -e '/Version: \(.*\)/s//\1/p')
 
-SFILE=/usr/games/lib/greed.hs
+SFILE=$(DESTDIR)/var/games/greed/greed.hs
 # Location of game executable
-BIN=/usr/games
+BIN=$(DESTDIR)/usr/games
 
 greed: greed.c
 	$(CC) -DSCOREFILE=\"$(SFILE)\" -DRELEASE=\"$(VERS)\" -o greed greed.c -O3 -lcurses
@@ -19,10 +19,10 @@
 
 install: greed.6 uninstall
 	cp greed $(BIN)
-	cp greed.6 /usr/share/man/man6/greed.6
+	cp greed.6 $(DESTDIR)/usr/share/man/man6/greed.6
 
 uninstall:
-	rm -f $(BIN)/install /usr/share/man/man6/greed.6
+	rm -f $(BIN)/greed $(DESTDIR)/usr/share/man/man6/greed.6
 
 clean:
 	rm -f *~ *.o greed greed-*.tar.gz  greed*.rpm *.html
